### ISSUE TITLE
The selected next lesson scrolls out of view

### ISSUE THREAD

**Issue by WhiskeyRomeoLima** [bushblade/TraversyMediaScrollActiveLesson#10]
At the end of a lesson, there is a popup with go-to next-lesson button.  Clicking on that button or letting the time expire, the menu scrolls up and the next lesson is out of view.  It is highlighted so it is easy to find.

**Comment by bushblade** [comment]
Hi @WhiskeyRomeoLima 
This would be more to do with the Kajabi platform and an issue for them to resolve really.
As such this isn't something I would want to try and remedy in the extension as it's likely to change and could then break the extension for the core functionality.
Hope that makes sense, I'll close here.
