### ISSUE TITLE
The left side menu does not scroll to the current lesson.

### ISSUE THREAD

**Issue by avrelungu** [bushblade/TraversyMediaScrollActiveLesson#11]
I currently experience a bug on the Chrome extension. Very rarely the scroll is done correctly. Most of the time whenever i click on a lesson, the scroll is barely making it to the end of the second section of the menu (eg : 1 - Variables, Data Types, Methods & More section on the JS course). It seems to me also that the problem occurs more if the clicked lesson belongs to a later lesson.

**Comment by bushblade** [comment]
Hi @avrelungu 
Thanks for this.
I can confirm I am seeing the same on Chromium.
What version of Chrome are you using?
I'll look into why this is happening when I have a bit of free time.
I can't reproduce the issue on FireFox though, so as a workaround I would suggest using FireFox for now.
Personally I much prefer the developer tools on FireFox too.

**Comment by bushblade** [comment]
Ok I've pinned the issue down to a problem with the `Element.scrollIntoView` and the `behavior: 'smooth'` option.
I can remove it so it instantly scrolls with no animation, or add a short delay before animating into view.
Either works, would you have a preference for behaviour?

**Comment by avrelungu** [comment]
Hello Will. That was fast. Probably adding a short delay would be more
aesthetically pleasing but either one works in my opinion.

Thanks for debugging have a great rest of the day

**Comment by bushblade** [comment]
Thanks @avrelungu 
I had to disable the smooth scrolling, it was still inconsistent even with the delay.
I've published the update, it can take a little time before the Chrome Web Store approve it, but it should automatically update when it is approved.
