### ISSUE TITLE
After installing React Developer tool may be effected.

### ISSUE THREAD

**Issue by WhiskeyRomeoLima** [bushblade/TraversyMediaScrollActiveLesson#3]
[EDIT] disregard.  After 20 minutes of working, React Dev tools started timing out again.
React Dev tool times out when clicking on components.
" Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received."

When I disabled the extension, React Dev tools performed as normal.

**Comment by bushblade** [comment]
Hi @WhiskeyRomeoLima 
I have React dev tools and the extension installed in both FireFox and Chromium and can't say I have see that.
Where are you seeing this please? Do you have a screenshot?
The Traversy Media website is built on the Kajabi platform and they use Preact, not React so you shouldn't really even see React dev tools extension available on traversymedia.com
The Traversy Media extension only runs on traversymedia.com/products i.e. course pages, so really should not interfere with any other unrelated extensions.
From what you have stated it sounds more like an issue in a project you are working on.
Are you sure this is the correct place to be raising an issue?

**Comment by WhiskeyRomeoLima** [comment]
Did you see the edit I added?  It said to disregard.  After about 20 minutes, with your extension disabled, the error showed up in react dev tools. 

 

Sorry for the inconvenience.From: Will Adams ***@***.*** ***@***.***>  
Sent: Thursday, June 22, 2023 1:32 PM
To: bushblade/TraversyMediaScrollActiveLesson ***@***.***>
Cc: William R Lucas ***@***.***>; Mention ***@***.***>
Subject: Re: [bushblade/TraversyMediaScrollActiveLesson] After installing React Developer tool may be effected. (Issue #3)

 

Hi @WhiskeyRomeoLima <https://github.com/WhiskeyRomeoLima> 
I have React dev tools and the extension installed in both FireFox and Chromium and can't say I have see that.
Where are you seeing this please? Do you have a screenshot?
The Traversy Media website is built on the Kajabi platform and they use Preact, not React so you shouldn't really even see React dev tools extension available on traversymedia.com
The Traversy Media extension only runs on traversymedia.com/products i.e. course pages, so really should not interfere with any other unrelated extensions.
From what you have stated it sounds more like an issue in a project you are working on.
Are you sure this is the correct place to be raising an issue?

**Comment by bushblade** [comment]
Hi again, yeah I did but it seemed a little ambiguous as to what that could mean depending on how you read it and the issue was not closed.
If you're good here then, I'll close.

**Comment by WhiskeyRomeoLima** [comment]
Yes close. I should have waited longer.  Again sorry for the inconvenience. Bill LucasOn Jun 22, 2023, at 1:54 PM, Will Adams ***@***.***> wrote:﻿
Hi again, yeah I did but it seemed a little ambiguous as to what that could mean depending on how you read it and the issue was not closed.
If you're good here then, I'll close.
