### ISSUE TITLE
Feature request: make the autoplay of the platform actually work

### ISSUE THREAD

**Issue by Archetipo95** [bushblade/TraversyMediaScrollActiveLesson#4]
I don't know if this is happening just to me, but the autoplay feature that tells me that the next video is going to start is not actually working.
I'd like to ask you if it's possible to implement this functionality in your extensions.

P.S.
Love your work! ❤️

**Comment by bushblade** [comment]
Hey @Archetipo95 
Thanks for the suggestion, I'll certainly look into if this is possible.

**Comment by Archetipo95** [comment]
I see this popup at the end of every video, but after 10s nothing happens, and it's bothering me so much 😆 
<img width="647" alt="Screenshot 2023-07-16 at 21 47 19" src="https://github.com/bushblade/TraversyMediaScrollActiveLesson/assets/11798239/5dd9880f-91e6-40ab-a044-b2fee2bb196e">

**Comment by bushblade** [comment]
Thanks for that @Archetipo95 
Strange though, I do not see the same thing. 
Instead I get a separate popup to ask if I want to go to the next lesson.....
![Screenshot_2023-07-16_21-02-54](https://github.com/bushblade/TraversyMediaScrollActiveLesson/assets/21976188/abf23da8-4119-44e6-8c4a-33b2314b7553)
I've never actually seen the popup you seem to have.

**Comment by bushblade** [comment]
Thanks for that.
I wonder if this is new as I've not seen it before and it took a force refresh (without cache) for me to see the same as you do.

**Comment by bushblade** [comment]
I have always got this popup (centre screen)...
![Screenshot_2023-07-16_21-07-01](https://github.com/bushblade/TraversyMediaScrollActiveLesson/assets/21976188/04b60201-c5dd-4ade-8da7-f921b606a6c7)

Which seems to conflict with the other popup in terms of UX as one is saying it's going to auto play and the other is prompting the user for a choice to start playing.
I feel this is a mistake on Kajabi's part, so it may be worth opening an issue with them though in my experience they don't really engage much.

**Comment by Archetipo95** [comment]
I was thinking about an autoclick feature just to skip to the next episode. Of course not everyone would like that, so the user should be able to choose.

**Comment by bushblade** [comment]
Yeah checking the code it looks like it's meant to be counting down and doesn't
I'll maybe keep an eye on it as I suspect it's broken on Kajabi's side of things so hopefully they will correct it, I would be reluctant to start fixing it in the extension if this is then going to change upstream so to speak.

**Comment by bushblade** [comment]
I think I'm gonna close this as something I won't fix as I feel this is more an issue with the Kajabi platform and should be addressed by them.
